### ISSUE TITLE
Xcode 12

### ISSUE THREAD

**Issue by grifas** [DataDome/IOSSDK-Example#5]
Hi, 

Impossible to build your app example on a simulator (but ok on a true device) with Xcode 12. There are a lot of errors like `undefined symbol` about DataDomeAlamofire.

How to fix that ?

Thanks

**Comment by meddatadome** [comment]
Hello @grifas ,

Please use Cocoapods 1.10 before running the app. Our new SDK is using the XCFramework format which cocoapods handles very poorly until version 1.10.

Thanks
